version: '3'
services:
  chess:
    image: "chess:latest"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: "python ./worker.py"
    environment:
      - HTTP_PORT=5000
